<a href="https://colab.research.google.com/github/Oseiasdfarias/ProbabilidadeProcessosEstocarticos/blob/main/lista_unidade_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>**2.1 – Tabela de Distribuição de Frequências**</center>



## Questão 1
A tabela a seguir apresenta dados referentes às idades dos funcionários da
empresa de engenharia fictícia. A média das idades é uma das informações que se deseja
calcular com base no conjunto de dados da tabela 1.


In [1]:
import numpy as np


In [2]:
primitiva = np.array([[18, 38, 36, 56, 52, 38, 39, 56, 54, 20],
                      [20, 30, 40, 32, 44, 44, 24, 28, 18, 30],
                      [48, 48, 42, 46, 40, 19, 27, 19, 42, 37],
                      [44, 34, 60, 18, 19, 36, 56, 26, 22, 28],
                      [30, 44, 48, 54, 36, 34, 36, 34, 21, 19],
                      [24, 52, 18, 28, 34, 60, 22, 28, 36, 26],
                      [24, 40, 27, 55, 60, 38, 24, 44, 36, 34],
                      [32, 34, 36, 44, 38, 40, 26, 48, 26, 28]
                      ])

In [3]:
primitiva

array([[18, 38, 36, 56, 52, 38, 39, 56, 54, 20],
       [20, 30, 40, 32, 44, 44, 24, 28, 18, 30],
       [48, 48, 42, 46, 40, 19, 27, 19, 42, 37],
       [44, 34, 60, 18, 19, 36, 56, 26, 22, 28],
       [30, 44, 48, 54, 36, 34, 36, 34, 21, 19],
       [24, 52, 18, 28, 34, 60, 22, 28, 36, 26],
       [24, 40, 27, 55, 60, 38, 24, 44, 36, 34],
       [32, 34, 36, 44, 38, 40, 26, 48, 26, 28]])

<br>

## a) Considere a Tabela 1, monte o ROL:


In [4]:
sorted_array = np.sort(primitiva, axis= None) 
print('The sorted array is:')
print(sorted_array)

The sorted array is:
[18 18 18 18 19 19 19 19 20 20 21 22 22 24 24 24 24 26 26 26 26 27 27 28
 28 28 28 28 30 30 30 32 32 34 34 34 34 34 34 36 36 36 36 36 36 36 37 38
 38 38 38 39 40 40 40 40 42 42 44 44 44 44 44 44 46 48 48 48 48 52 52 54
 54 55 56 56 56 60 60 60]


<br>

## b) Considere o ROL montado no item “a”. Montar a Tabela de Distribuição de Frequência por Valores (TDF por Valores):


In [5]:
unique, counts = np.unique(sorted_array, return_counts=True)
dist = np.asarray((unique, counts)).T
print(dist)

[[18  4]
 [19  4]
 [20  2]
 [21  1]
 [22  2]
 [24  4]
 [26  4]
 [27  2]
 [28  5]
 [30  3]
 [32  2]
 [34  6]
 [36  7]
 [37  1]
 [38  4]
 [39  1]
 [40  4]
 [42  2]
 [44  6]
 [46  1]
 [48  4]
 [52  2]
 [54  2]
 [55  1]
 [56  3]
 [60  3]]


# <center>**2.2 – Elaboração da TDF**</center>

## Questão 2 – Considere o ROL (questão 1.a):


## a) Calcular a Amplitude Total (AT):


Solução:

$$AT = X_{max} - X_{min}$$

$$AT = 60 - 18$$

$$AT = 42$$

<br>

In [6]:
at = np.max(primitiva) - np.min(primitiva[:1,:1])
print(f"Amplitude Total: {at}")

Amplitude Total: 42


## b) Calcular o Número de Classes (K):


<br>

Regra de Sturges

$$K = \sqrt{N}$$
$$K = \sqrt{80}$$
$$K \approx 9$$

<br>


In [7]:
n = primitiva.shape[0]*primitiva.shape[1]
k = np.sqrt(n)
print(f"Número de Classes (K): {k}")


Número de Classes (K): 8.94427190999916


<br>

## c) Calcular a Amplitude da Classe (h):


$$h \approx \dfrac{AT}{K}$$

$$Teste: h \times K \geq AT$$

$$h \approx \dfrac{42}{9} = 5$$

$$Teste: h \times K \geq AT = True$$ 

In [8]:
h = at / k
h = round(h)
print(f"Amplitude da Classe (h): {h}")

Amplitude da Classe (h): 5


Teste:

In [9]:
h*k >= at


True

<br>

## d) Montar a Tabela de Distribuição de Frequência por Classes (TDF por Classes) de acordo com os valores calculadas:

| index 	| início 	| fim 	| frequência | Percentual % 
|----	    |----	    |----	  | ---        | ---
| 1° 	    | 18 	    | 23 	  | 13         | 16.25%
| 2° 	    | 23 	    | 28   	| 10         | 12.50%
| 3° 	    | 28 	    | 33 	  | 10         | 12.50%
| 4° 	    | 33    	| 38 	  | 14         | 17.50%
| 5° 	    | 38 	    | 43   	| 11         | 13.75%
| 6° 	    | 43    	| 48 	  | 07         | 08.75%
| 7° 	    | 48    	| 52 	  | 04         | 05.00%
| 8°    	| 52    	| 53 	  | 02         | 02.50%
| 9° 	    | 53 	    | 63 	  | 09         | 11.25%


<br>

In [45]:
init = 18

# Coluna de frequencia da tabela de frequencia
freq_t = np.array([13, 10, 10, 14, 11, 7, 4, 2, 9])
perc = np.zeros((1, 9), dtype="float32")

freq_t.sum()

# Coluna de Percentual da tabela de frequencia
for i, j in enumerate(freq_t):
  perc[0][i] = (100*j)/80

print("\nTabela de Distribuição de Frequências\n")
for i in range(9):
  print(init, end=" ")
  init += 5
  print(init, end="     ")
  print(freq_t[i], end="")
  print(f"         {perc[0][i]}%")



Tabela de Distribuição de Frequências

18 23     13         16.25%
23 28     10         12.5%
28 33     10         12.5%
33 38     14         17.5%
38 43     11         13.75%
43 48     7         8.75%
48 53     4         5.0%
53 58     2         2.5%
58 63     9         11.25%


In [47]:
# Coluna dos intervalos da tabela de frequência

freq_tab = np.array([ [18, 23],
                      [23, 28],
                      [28, 33],
                      [33, 38],
                      [38, 43],
                      [43, 48],
                      [48, 53],
                      [53, 58],
                      [58, 63]])
print(freq_tab)

[[18 23]
 [23 28]
 [28 33]
 [33 38]
 [38 43]
 [43 48]
 [48 53]
 [53 58]
 [58 63]]
